#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from subprocess import check_call

try:
    from urllib.parse import urlparse
except ImportError:
    from urlparse import urlparse


import logging
_logger = logging.getLogger(__name__)

# Recreate and run git-aggregator
SOURCES = os.environ.get('SOURCES')
RESOURCES = os.environ.get('RESOURCES')
REPOS_YML = os.environ.get('REPOS_YML')

if REPOS_YML and SOURCES:
    content = urllib.parse.unquote(REPOS_YML)
    repos_file = os.path.join(RESOURCES, "custom-repos.yml")
    with open(repos_file, 'w+') as file:
        file.write(content)

    _logger.info('Running git aggregator on custom-repos.yml..')
    check_call([
        'autoaggregate',
        '--config',
        repos_file,
        '--install',
        '--output',
        os.path.join(SOURCES, 'repositories'),
    ])
